# Generated by Django 5.0 on 2024-01-22 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('_id', models.CharField(max_length=17, unique=True)),
                ('date_setup', models.BigIntegerField()),
                ('last_setup', models.BigIntegerField()),
                ('device_type', models.CharField(max_length=255)),
                ('last_status_store', models.BigIntegerField()),
                ('firmware', models.IntegerField()),
                ('last_upgrade', models.IntegerField()),
                ('wifi_status', models.IntegerField()),
                ('reachable', models.BooleanField()),
                ('co2_calibrating', models.BooleanField()),
                ('station_name', models.CharField(max_length=255)),
                ('read_only', models.BooleanField()),
                ('data_type', models.CharField(max_length=255)),
                ('subtype', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('altitude', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('timezone', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=254)),
                ('lang', models.CharField(max_length=255)),
                ('reg_locale', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('windunit', models.IntegerField()),
                ('pressureunit', models.IntegerField()),
                ('feel_like_algo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_utc', models.BigIntegerField()),
                ('temperature', models.FloatField()),
                ('co2', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('noise', models.IntegerField()),
                ('pressure', models.FloatField()),
                ('absolutePressure', models.FloatField()),
                ('health_idx', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_almacenamiento_json.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_almacenamiento_json.place'),
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio_almacenamiento_json.users'),
        ),
    ]
